### ISSUE TITLE
`chachalog comment-pr` runs in the wrong repo

### ISSUE THREAD

**Issue by GauBen** [GauBen/chachalog#32]
Because `comment-pr` runs with this trigger

```yaml
on:
  pull_request:
    branches: [main]
```

it may run on a fork. We don't want to comment the fork (permission will be denied) but the *target* repository.
